Traceback (most recent call last):
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kristian/miniforge3/envs/tf_M1/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Savitsky-Golay filter
from scipy.signal import savgol_filter
yhat = savgol_filter(y+noise, 51, 3) # window size 51, polynomial order 3
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn [7], line 3[0m
[1;32m      1[0m [38;5;66;03m# Savitsky-Golay filter[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01msignal[39;00m [38;5;28;01mimport[39;00m savgol_filter
[0;32m----> 3[0m yhat [38;5;241m=[39m savgol_filter([43my[49m[38;5;241;43m+[39;49m[43mnoise[49m, [38;5;241m51[39m, [38;5;241m3[39m) [38;5;66;03m# window size 51, polynomial order 3[39;00m

[0;31mValueError[0m: operands could not be broadcast together with shapes (301,) (500,) 
ValueError: operands could not be broadcast together with shapes (301,) (500,) 

